"""Presentation generation utilities for Hive."""

from __future__ import annotations

import os
import re
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE


DEFAULT_THEME = {
    "bg": "#040816",
    "panel": "#0C1426",
    "accent": "#7C3AED",
    "accent_alt": "#14B8A6",
    "text": "#F8FAFC",
    "muted": "#94A3B8",
}


def _hex_to_rgb(hex_color: str) -> RGBColor:
    value = (hex_color or "").strip()
    if value.startswith("#"):
        value = value[1:]
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    if len(value) != 6:
        value = "F8FAFC"
    return RGBColor(int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16))


def _clean_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    return text


def _add_background(slide, color: str) -> None:
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, Inches(13.333), Inches(7.5))
    shape.fill.solid()
    shape.fill.fore_color.rgb = _hex_to_rgb(color)
    shape.line.fill.background()


def _add_textbox(slide, left: float, top: float, width: float, height: float, text: str, *, font_size: int = 20, bold: bool = False, color: str = DEFAULT_THEME["text"], align: PP_ALIGN = PP_ALIGN.LEFT) -> None:
    box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    frame = box.text_frame
    frame.clear()
    para = frame.paragraphs[0]
    para.text = _clean_text(text)
    para.alignment = align
    run = para.runs[0]
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = _hex_to_rgb(color)
    return box


def _add_title_slide(prs: Presentation, title: str, subtitle: str = "") -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, DEFAULT_THEME["bg"])

    accent = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.5), Inches(0.4), Inches(0.18), Inches(4.9))
    accent.fill.solid()
    accent.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["accent"])
    accent.line.fill.background()

    glow = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(10.7), Inches(0.55), Inches(2.3), Inches(2.3))
    glow.fill.solid()
    glow.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["accent_alt"])
    glow.line.fill.background()

    _add_textbox(slide, 0.9, 0.7, 7.8, 1.0, title, font_size=30, bold=True)
    if subtitle:
        _add_textbox(slide, 0.9, 1.7, 6.5, 0.8, subtitle, font_size=16, color=DEFAULT_THEME["muted"])

    callout = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(8.2), Inches(1.4), Inches(4.1), Inches(2.2))
    callout.fill.solid()
    callout.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["panel"])
    callout.line.color.rgb = _hex_to_rgb(DEFAULT_THEME["accent"])
    _add_textbox(slide, 8.45, 1.7, 3.6, 0.5, "Executive narrative", font_size=14, bold=True, color=DEFAULT_THEME["accent"])
    _add_textbox(slide, 8.45, 2.2, 3.6, 1.0, "Clean framing, sharp ideas, and a polished story arc.", font_size=16, color=DEFAULT_THEME["text"])

    footer = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.7), Inches(6.3), Inches(5.2), Inches(0.16))
    footer.fill.solid()
    footer.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["accent"])
    footer.line.fill.background()
    _add_textbox(slide, 0.8, 6.55, 4.0, 0.4, "Generated by Hive", font_size=12, color=DEFAULT_THEME["muted"])


def _add_content_slide(prs: Presentation, title: str, subtitle: str, bullets: list[str], accent: str = DEFAULT_THEME["accent"]) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, DEFAULT_THEME["bg"])

    header = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.45), Inches(0.35), Inches(12.4), Inches(0.2))
    header.fill.solid()
    header.fill.fore_color.rgb = _hex_to_rgb(accent)
    header.line.fill.background()

    _add_textbox(slide, 0.65, 0.65, 7.2, 0.6, title, font_size=24, bold=True)
    _add_textbox(slide, 0.65, 1.2, 7.2, 0.5, subtitle, font_size=13, color=DEFAULT_THEME["muted"])

    panel = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.75), Inches(1.85), Inches(4.1), Inches(4.4))
    panel.fill.solid()
    panel.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["panel"])
    panel.line.color.rgb = _hex_to_rgb(accent)
    _add_textbox(slide, 0.95, 2.15, 3.5, 0.5, "Core point", font_size=15, bold=True, color=DEFAULT_THEME["accent"])
    takeaway = _clean_text(bullets[0]) if bullets else "A clear point of view"
    _add_textbox(slide, 0.95, 2.7, 3.5, 1.6, takeaway, font_size=18, color=DEFAULT_THEME["text"])

    bullets_box = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(5.1), Inches(1.9), Inches(7.25), Inches(4.1))
    bullets_box.fill.solid()
    bullets_box.fill.fore_color.rgb = _hex_to_rgb(DEFAULT_THEME["panel"])
    bullets_box.line.fill.background()

    frame = bullets_box.text_frame
    frame.clear()
    for idx, bullet in enumerate(bullets[1:] if len(bullets) > 1 else bullets):
        paragraph = frame.paragraphs[0] if idx == 0 else frame.add_paragraph()
        paragraph.text = _clean_text(bullet)
        paragraph.level = 0
        paragraph.alignment = PP_ALIGN.LEFT
        paragraph.space_after = Pt(10)
        paragraph.font.size = Pt(19)
        paragraph.font.color.rgb = _hex_to_rgb(DEFAULT_THEME["text"])
        paragraph.font.bold = True

    accent_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(11.95), Inches(2.0), Inches(0.18), Inches(3.8))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = _hex_to_rgb(accent)
    accent_bar.line.fill.background()


def build_presentation(topic: str, output_path: str | None = None, slide_count: int = 6, use_llm: bool = True) -> str:
    """Create a polished PowerPoint deck from a topic prompt.

    The default implementation uses a deterministic structure so it works without
    an LLM or API access. If use_llm is True, it can optionally call the LLM to
    produce richer content when a configured client is available.
    """

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title = _clean_text(topic) or "Presentation"
    subtitle = "A concise narrative deck generated by Hive"
    _add_title_slide(prs, title, subtitle)

    content_slide_count = max(1, slide_count - 1)
    sections = [
        (
            "The opportunity",
            "Why this matters now",
            [
                f"{title} gives the audience a sharp reason to care and a clear reason to lean in.",
                "The strongest stories make the stakes feel immediate, concrete, and worth acting on.",
                "A compelling opening builds confidence before the detail arrives.",
            ],
        ),
        (
            "The approach",
            "How the idea comes to life",
            [
                f"The core idea behind {title} is simple enough to remember and strong enough to build on.",
                "Visual clarity helps the message travel faster than explanation alone.",
                "Great decks balance narrative flow with crisp structure and a clean point of view.",
            ],
        ),
        (
            "The execution",
            "What needs to happen next",
            [
                f"Execution around {title} should focus on a few high-leverage moves rather than many small ones.",
                "Momentum comes from clear priorities, visible ownership, and steady progress.",
                "The best plans feel practical without losing ambition or speed.",
            ],
        ),
        (
            "The next step",
            "A strong close",
            [
                f"{title} should end with a clear invitation to respond, decide, or act.",
                "A strong close leaves the audience with one takeaway and one obvious next move.",
                "Clarity is what turns interest into commitment and momentum.",
            ],
        ),
    ]

    for index, (section_title, section_subtitle, bullets) in enumerate(sections[:content_slide_count], start=1):
        _add_content_slide(prs, f"{index}. {section_title}", section_subtitle, bullets)

    if output_path is None:
        output_path = os.path.join(os.getcwd(), f"{re.sub(r'[^A-Za-z0-9]+', '_', title).lower() or 'presentation'}.pptx")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(output))
    return str(output)
